# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d0fac477040f68425f59e59c2e4977010e18cb8e3bbf0578ab174c804234a52d133764854d0dd15978c5d1a1085ac05e3d56098eeada7f122f118262c9d62b2

test:
  secret_key_base: 86d0eebbb9ef3a40b6fa48263d545dc71d0f61adacbaccbbf462160155b719aca0d8160f8138f8d5dda5f4798282dfeb807876b9f9bbc9bd42e2488b7c74e63d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
